name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push event only for all branches
  push:
 #   branches: [ main, master, develop ]

  #pull_request:
  #  branches: [ main, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  setup-sdk:
    runs-on: ubuntu-24.04

    steps:
      - name: Cache sdk
        id: cache-sdk
        uses: actions/cache@v4
        with:
          path: |
             cc65/**/*
             orix-sdk/**/*
             md2hlp/**/*
             orix-software/**/*
             bpm/**/*
             oricutron/**/*
          key: ${{ secrets.CACHE_ID }}-orix-sdk

      - name: Checkout cc65
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: cc65/cc65
          path: cc65

      - name: Checkout bpm
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: orix-software/bpm
          path: bpm

      - name: Checkout orix-sdk
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: assinie/orix-sdk
          path: orix-sdk

      - name: Checkout md2hlp
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: assinie/md2hlp
          path: md2hlp

      - name: Compilation CC65
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: make -C cc65 >/dev/null

      - name: Prepare environment for orix-sdk
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          git clone --no-checkout --depth 1 --single-branch --branch master https://github.com/orix-software/shell orix-software/shell
          cd orix-software/shell
          git config --local core.sparseCheckout true
          echo "src/include" >> .git/info/sparse-checkout
          git checkout
          cd ../..
          git clone --no-checkout --depth 1 --single-branch --branch master https://github.com/orix-software/kernel orix-software/kernel
          cd orix-software/kernel
          git config --local core.sparseCheckout true
          echo "src/include" >> .git/info/sparse-checkout
          git checkout

      - name: Prepare environment for oricutron
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb libgtk-3-0 libgtk-3-dev libsdl1.2debian libsdl1.2-dev
          git clone https://github.com/pete-gordon/oricutron.git
          cd oricutron && make && pwd && cd .. && ls -l && echo ${GITHUB_WORKSPACE}
          echo Timeout oricutron : ${secret}.TMOUT_ORICUTRON

      - name: Compile orix-sdk
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        working-directory: orix-sdk
        run: mkdir -p build/{lib,bin} && CC65_HOME=${GITHUB_WORKSPACE}/cc65 make lib

      - name: Display tools
        run: |
          PATH=$PATH:${GITHUB_WORKSPACE}/cc65/bin
          cc65 -V
          ls -lR orix-sdk
          ls -l cc65/bin

  build:
    # The type of runner that the job will run on
    needs: setup-sdk
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.job_vars.outputs.VERSION }}
      repo_name: ${{ steps.job_vars.outputs.REPO_NAME }}
      bpm_found: ${{ steps.bpm_upload.outputs.BPM_FOUND }}

    steps:
      - uses: actions/checkout@v3

      - name: Set job variables
        id: job_vars
        run: |
          echo "::set-output name=VERSION::$(cat VERSION)"
          echo "::set-output name=REPO_NAME::${GITHUB_REPOSITORY##*/}"

      - name: Install sdk
        uses: actions/cache@v4
        with:
          path: |
             cc65/**/*
             orix-sdk/**/*
             md2hlp/**/*
             orix-software/**/*
             bpm/**/*
             oricutron/**/*
          key: ${{ secrets.CACHE_ID }}-orix-sdk

      - name: Prepare environment for project
        run: |
          mkdir ~/bin
          cd bpm && pip install -r requirements.txt && cd ..
          mv cc65 ../ && mv orix-software ../ && mv orix-sdk ../ && mv md2hlp ../ && mv bpm ../

      - name: Compile project
        run: |
          if [ -f "bpm.tml" ]; then
            chmod 755 ../bpm/src/bpm
            echo "../bpm/src/bpm" >> $GITHUB_PATH
            export PATH=$PATH:../bpm/src/:${GITHUB_WORKSPACE}/../cc65/bin
            bpm --force-update --replace-for-new-project -V
          fi
          CC65_HOME=${GITHUB_WORKSPACE}/../cc65 ./make.sh

      - name: List build directory content
        run: ls -lR build

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.job_vars.outputs.REPO_NAME }}
          path: |
            build/**/*
            !build/obj/*

      - name: Post compilation
        run: mv ../cc65 . && mv ../orix-software . && mv ../orix-sdk . && mv ../md2hlp .

      - name: Upload if bpm
        id: bpm_upload
        run: |
          ls -l
          if [ -f "bpm.tml" ]; then
            export BPM_PUBLISH_KEY=$hash
            export PATH=$PATH:../bpm/src/:${GITHUB_WORKSPACE}/../cc65/bin
            if [ "$BRANCH_NAME" = "master" -o "$BRANCH_NAME" = "main" ]; then bpm --force-update -V;--force-update publish --official; else bpm publish --alpha; fi
            echo "BPM_FOUND=True" >> $GITHUB_OUTPUT
          else
            echo "bpm.tml not found, skipping bpm upload"
          fi

